### ISSUE TITLE
Refactor Meta Generator to use Link and re-brand it as the Link Generator

### ISSUE THREAD

**Issue by AlexLakatos** [WICG/webmonetization#315]
Currently, https://webmonetization.org/meta-tag helps you generate a meta tag with a payment pointer. That's designed for the old Web Monetization specification.

We should update the page & generator functionality to conform with the new Web Monetization spec, that uses link tags instead of meta tags. https://webmonetization-preview.netlify.app/specification.html

- [x] Rename "Meta Tag Generator" to "Link Tag Generator"
- [x] Remove the option to "Use receipt verifier service". Receipts are deprecated in the new spec.
- [x] Change output to use `<link rel="monetization" href="https://example.com/payment-pointer">` instead of `<meta name="monetization" content="$example.com/payment-pointer" />`
- [x] Add functionality to convert/support both payment pointer notations in the input ($ilp.dev and https://ilp.dev are equivalent). Both forms of payment pointers should generate the link with https, not with $

Note: link tags are supported throughout the document, not just in the head.

**Comment by huijing** [comment]
## Dev notes

1. Should we rename the slug to `link-tag` and add a redirect from /meta-tag to /link-tag?

**Comment by melissahenderson** [comment]
Can we change the default example that shows before you manually add your payment pointer from:

`<link rel="monetization" href="$YourPaymentPointer" />`

to

`<link rel="monetization" href="https://YourPaymentPointer" />`
